# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Small World Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Small World Task
  pod 'Alamofire', '5.5.0'
  pod 'SDWebImage', '5.15.5'
  

  post_install do |installer|
     installer.pods_project.build_configurations.each do |config|
     end
     installer.generated_projects.each do |project|
           project.targets.each do |target|
               target.build_configurations.each do |config|
                   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
                end
           end
    end
   end

end
